<?php

namespace Omed\CMS\Tests;

use ApiPlatform\Symfony\Bundle\Test\ApiTestCase;
use Omed\CMS\DataFixtures\Factory\ArticleFactory;
use Zenstruck\Foundry\Test\Factories;
use Zenstruck\Foundry\Test\ResetDatabase;

/**
 * @covers \Omed\CMS\Entity\Article
 */
class ArticleTest extends ApiTestCase
{
    use ResetDatabase, Factories;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        static::$alwaysBootKernel = true;
    }

    public function testGetArticles(): void
    {
        ArticleFactory::createMany(5);


        $response = static::createClient()->request('GET', '/articles');
        $this->assertResponseIsSuccessful();
        $this->assertResponseHeaderSame('content-type',  'application/ld+json; charset=utf-8');
        $this->assertCount(5, $response->toArray()['member']);
        $this->assertNotNull($response->toArray()['member'][0]);

        $ob = $response->toArray()['member'][0];
        $this->assertNotNull($ob['slug']);
    }
}
