// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kilip/omed/finance/ent/account"
	"github.com/kilip/omed/finance/ent/internal"
	"github.com/kilip/omed/finance/ent/predicate"
	"github.com/kilip/omed/finance/ent/user"
	"github.com/kilip/omed/finance/ent/workspace"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *AccountUpdate) SetUpdatedAt(v time.Time) *AccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceId sets the "workspaceId" field.
func (_u *AccountUpdate) SetWorkspaceId(v uuid.UUID) *AccountUpdate {
	_u.mutation.SetWorkspaceId(v)
	return _u
}

// SetNillableWorkspaceId sets the "workspaceId" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableWorkspaceId(v *uuid.UUID) *AccountUpdate {
	if v != nil {
		_u.SetWorkspaceId(*v)
	}
	return _u
}

// SetCreatedBy sets the "createdBy" field.
func (_u *AccountUpdate) SetCreatedBy(v uuid.UUID) *AccountUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableCreatedBy(v *uuid.UUID) *AccountUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *AccountUpdate) SetUpdatedBy(v uuid.UUID) *AccountUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableUpdatedBy(v *uuid.UUID) *AccountUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetParentId sets the "parentId" field.
func (_u *AccountUpdate) SetParentId(v uuid.UUID) *AccountUpdate {
	_u.mutation.SetParentId(v)
	return _u
}

// SetNillableParentId sets the "parentId" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableParentId(v *uuid.UUID) *AccountUpdate {
	if v != nil {
		_u.SetParentId(*v)
	}
	return _u
}

// ClearParentId clears the value of the "parentId" field.
func (_u *AccountUpdate) ClearParentId() *AccountUpdate {
	_u.mutation.ClearParentId()
	return _u
}

// SetCode sets the "code" field.
func (_u *AccountUpdate) SetCode(v string) *AccountUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableCode(v *string) *AccountUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdate) SetName(v string) *AccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableName(v *string) *AccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AccountUpdate) SetType(v account.Type) *AccountUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableType(v *account.Type) *AccountUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDetailType sets the "detailType" field.
func (_u *AccountUpdate) SetDetailType(v account.DetailType) *AccountUpdate {
	_u.mutation.SetDetailType(v)
	return _u
}

// SetNillableDetailType sets the "detailType" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableDetailType(v *account.DetailType) *AccountUpdate {
	if v != nil {
		_u.SetDetailType(*v)
	}
	return _u
}

// SetNormalBalance sets the "normalBalance" field.
func (_u *AccountUpdate) SetNormalBalance(v account.NormalBalance) *AccountUpdate {
	_u.mutation.SetNormalBalance(v)
	return _u
}

// SetNillableNormalBalance sets the "normalBalance" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableNormalBalance(v *account.NormalBalance) *AccountUpdate {
	if v != nil {
		_u.SetNormalBalance(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *AccountUpdate) SetCurrency(v string) *AccountUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableCurrency(v *string) *AccountUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetIsPlaceholder sets the "isPlaceholder" field.
func (_u *AccountUpdate) SetIsPlaceholder(v bool) *AccountUpdate {
	_u.mutation.SetIsPlaceholder(v)
	return _u
}

// SetNillableIsPlaceholder sets the "isPlaceholder" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIsPlaceholder(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetIsPlaceholder(*v)
	}
	return _u
}

// SetIsSystem sets the "isSystem" field.
func (_u *AccountUpdate) SetIsSystem(v bool) *AccountUpdate {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "isSystem" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIsSystem(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *AccountUpdate) SetIsActive(v bool) *AccountUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIsActive(v *bool) *AccountUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetWorkspaceID sets the "workspace" edge to the Workspace entity by ID.
func (_u *AccountUpdate) SetWorkspaceID(id uuid.UUID) *AccountUpdate {
	_u.mutation.SetWorkspaceID(id)
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *AccountUpdate) SetWorkspace(v *Workspace) *AccountUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *AccountUpdate) SetCreatorID(id uuid.UUID) *AccountUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *AccountUpdate) SetCreator(v *User) *AccountUpdate {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *AccountUpdate) SetUpdaterID(id uuid.UUID) *AccountUpdate {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *AccountUpdate) SetUpdater(v *User) *AccountUpdate {
	return _u.SetUpdaterID(v.ID)
}

// SetParentID sets the "parent" edge to the Account entity by ID.
func (_u *AccountUpdate) SetParentID(id uuid.UUID) *AccountUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Account entity by ID if the given value is not nil.
func (_u *AccountUpdate) SetNillableParentID(id *uuid.UUID) *AccountUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Account entity.
func (_u *AccountUpdate) SetParent(v *Account) *AccountUpdate {
	return _u.SetParentID(v.ID)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *AccountUpdate) ClearWorkspace() *AccountUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *AccountUpdate) ClearCreator() *AccountUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *AccountUpdate) ClearUpdater() *AccountUpdate {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearParent clears the "parent" edge to the Account entity.
func (_u *AccountUpdate) ClearParent() *AccountUpdate {
	_u.mutation.ClearParent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := account.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Account.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := account.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Account.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DetailType(); ok {
		if err := account.DetailTypeValidator(v); err != nil {
			return &ValidationError{Name: "detailType", err: fmt.Errorf(`ent: validator failed for field "Account.detailType": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalBalance(); ok {
		if err := account.NormalBalanceValidator(v); err != nil {
			return &ValidationError{Name: "normalBalance", err: fmt.Errorf(`ent: validator failed for field "Account.normalBalance": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := account.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Account.currency": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.workspace"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.updater"`)
	}
	return nil
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ParentId(); ok {
		_spec.SetField(account.FieldParentId, field.TypeUUID, value)
	}
	if _u.mutation.ParentIdCleared() {
		_spec.ClearField(account.FieldParentId, field.TypeUUID)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(account.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(account.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DetailType(); ok {
		_spec.SetField(account.FieldDetailType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NormalBalance(); ok {
		_spec.SetField(account.FieldNormalBalance, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(account.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPlaceholder(); ok {
		_spec.SetField(account.FieldIsPlaceholder, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(account.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(account.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.WorkspaceTable,
			Columns: []string{account.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.WorkspaceTable,
			Columns: []string{account.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.CreatorTable,
			Columns: []string{account.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.CreatorTable,
			Columns: []string{account.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.UpdaterTable,
			Columns: []string{account.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.UpdaterTable,
			Columns: []string{account.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   account.ParentTable,
			Columns: []string{account.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   account.ParentTable,
			Columns: []string{account.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Account
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *AccountUpdateOne) SetUpdatedAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceId sets the "workspaceId" field.
func (_u *AccountUpdateOne) SetWorkspaceId(v uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetWorkspaceId(v)
	return _u
}

// SetNillableWorkspaceId sets the "workspaceId" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableWorkspaceId(v *uuid.UUID) *AccountUpdateOne {
	if v != nil {
		_u.SetWorkspaceId(*v)
	}
	return _u
}

// SetCreatedBy sets the "createdBy" field.
func (_u *AccountUpdateOne) SetCreatedBy(v uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *AccountUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *AccountUpdateOne) SetUpdatedBy(v uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *AccountUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetParentId sets the "parentId" field.
func (_u *AccountUpdateOne) SetParentId(v uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetParentId(v)
	return _u
}

// SetNillableParentId sets the "parentId" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableParentId(v *uuid.UUID) *AccountUpdateOne {
	if v != nil {
		_u.SetParentId(*v)
	}
	return _u
}

// ClearParentId clears the value of the "parentId" field.
func (_u *AccountUpdateOne) ClearParentId() *AccountUpdateOne {
	_u.mutation.ClearParentId()
	return _u
}

// SetCode sets the "code" field.
func (_u *AccountUpdateOne) SetCode(v string) *AccountUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableCode(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AccountUpdateOne) SetName(v string) *AccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableName(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AccountUpdateOne) SetType(v account.Type) *AccountUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableType(v *account.Type) *AccountUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDetailType sets the "detailType" field.
func (_u *AccountUpdateOne) SetDetailType(v account.DetailType) *AccountUpdateOne {
	_u.mutation.SetDetailType(v)
	return _u
}

// SetNillableDetailType sets the "detailType" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableDetailType(v *account.DetailType) *AccountUpdateOne {
	if v != nil {
		_u.SetDetailType(*v)
	}
	return _u
}

// SetNormalBalance sets the "normalBalance" field.
func (_u *AccountUpdateOne) SetNormalBalance(v account.NormalBalance) *AccountUpdateOne {
	_u.mutation.SetNormalBalance(v)
	return _u
}

// SetNillableNormalBalance sets the "normalBalance" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableNormalBalance(v *account.NormalBalance) *AccountUpdateOne {
	if v != nil {
		_u.SetNormalBalance(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *AccountUpdateOne) SetCurrency(v string) *AccountUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableCurrency(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetIsPlaceholder sets the "isPlaceholder" field.
func (_u *AccountUpdateOne) SetIsPlaceholder(v bool) *AccountUpdateOne {
	_u.mutation.SetIsPlaceholder(v)
	return _u
}

// SetNillableIsPlaceholder sets the "isPlaceholder" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIsPlaceholder(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetIsPlaceholder(*v)
	}
	return _u
}

// SetIsSystem sets the "isSystem" field.
func (_u *AccountUpdateOne) SetIsSystem(v bool) *AccountUpdateOne {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "isSystem" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIsSystem(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *AccountUpdateOne) SetIsActive(v bool) *AccountUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIsActive(v *bool) *AccountUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetWorkspaceID sets the "workspace" edge to the Workspace entity by ID.
func (_u *AccountUpdateOne) SetWorkspaceID(id uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetWorkspaceID(id)
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *AccountUpdateOne) SetWorkspace(v *Workspace) *AccountUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *AccountUpdateOne) SetCreatorID(id uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *AccountUpdateOne) SetCreator(v *User) *AccountUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *AccountUpdateOne) SetUpdaterID(id uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *AccountUpdateOne) SetUpdater(v *User) *AccountUpdateOne {
	return _u.SetUpdaterID(v.ID)
}

// SetParentID sets the "parent" edge to the Account entity by ID.
func (_u *AccountUpdateOne) SetParentID(id uuid.UUID) *AccountUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Account entity by ID if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableParentID(id *uuid.UUID) *AccountUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Account entity.
func (_u *AccountUpdateOne) SetParent(v *Account) *AccountUpdateOne {
	return _u.SetParentID(v.ID)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *AccountUpdateOne) ClearWorkspace() *AccountUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *AccountUpdateOne) ClearCreator() *AccountUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *AccountUpdateOne) ClearUpdater() *AccountUpdateOne {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearParent clears the "parent" edge to the Account entity.
func (_u *AccountUpdateOne) ClearParent() *AccountUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := account.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Account.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := account.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Account.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DetailType(); ok {
		if err := account.DetailTypeValidator(v); err != nil {
			return &ValidationError{Name: "detailType", err: fmt.Errorf(`ent: validator failed for field "Account.detailType": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalBalance(); ok {
		if err := account.NormalBalanceValidator(v); err != nil {
			return &ValidationError{Name: "normalBalance", err: fmt.Errorf(`ent: validator failed for field "Account.normalBalance": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := account.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Account.currency": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.workspace"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.updater"`)
	}
	return nil
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ParentId(); ok {
		_spec.SetField(account.FieldParentId, field.TypeUUID, value)
	}
	if _u.mutation.ParentIdCleared() {
		_spec.ClearField(account.FieldParentId, field.TypeUUID)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(account.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(account.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DetailType(); ok {
		_spec.SetField(account.FieldDetailType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NormalBalance(); ok {
		_spec.SetField(account.FieldNormalBalance, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(account.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPlaceholder(); ok {
		_spec.SetField(account.FieldIsPlaceholder, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(account.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(account.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.WorkspaceTable,
			Columns: []string{account.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.WorkspaceTable,
			Columns: []string{account.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.CreatorTable,
			Columns: []string{account.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.CreatorTable,
			Columns: []string{account.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.UpdaterTable,
			Columns: []string{account.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.UpdaterTable,
			Columns: []string{account.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   account.ParentTable,
			Columns: []string{account.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   account.ParentTable,
			Columns: []string{account.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Account
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
