// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kilip/omed/finance/ent/account"
	"github.com/kilip/omed/finance/ent/user"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedBy sets the "createdBy" field.
func (_c *AccountCreate) SetCreatedBy(v uuid.UUID) *AccountCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *AccountCreate) SetCreatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *AccountCreate) SetNillableCreatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updatedBy" field.
func (_c *AccountCreate) SetUpdatedBy(v uuid.UUID) *AccountCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *AccountCreate) SetUpdatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *AccountCreate) SetNillableUpdatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *AccountCreate) SetWorkspaceID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *AccountCreate) SetCode(v string) *AccountCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *AccountCreate) SetName(v string) *AccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AccountCreate) SetDescription(v string) *AccountCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AccountCreate) SetNillableDescription(v *string) *AccountCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *AccountCreate) SetType(v account.Type) *AccountCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *AccountCreate) SetCurrency(v string) *AccountCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccountCreate) SetStatus(v account.Status) *AccountCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AccountCreate) SetNillableStatus(v *account.Status) *AccountCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetParentId sets the "parentId" field.
func (_c *AccountCreate) SetParentId(v uuid.UUID) *AccountCreate {
	_c.mutation.SetParentId(v)
	return _c
}

// SetNillableParentId sets the "parentId" field if the given value is not nil.
func (_c *AccountCreate) SetNillableParentId(v *uuid.UUID) *AccountCreate {
	if v != nil {
		_c.SetParentId(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountCreate) SetID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AccountCreate) SetNillableID(v *uuid.UUID) *AccountCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *AccountCreate) SetCreatorID(id uuid.UUID) *AccountCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *AccountCreate) SetCreator(v *User) *AccountCreate {
	return _c.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_c *AccountCreate) SetUpdaterID(id uuid.UUID) *AccountCreate {
	_c.mutation.SetUpdaterID(id)
	return _c
}

// SetUpdater sets the "updater" edge to the User entity.
func (_c *AccountCreate) SetUpdater(v *User) *AccountCreate {
	return _c.SetUpdaterID(v.ID)
}

// SetParentID sets the "parent" edge to the Account entity by ID.
func (_c *AccountCreate) SetParentID(id uuid.UUID) *AccountCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the Account entity by ID if the given value is not nil.
func (_c *AccountCreate) SetNillableParentID(id *uuid.UUID) *AccountCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the Account entity.
func (_c *AccountCreate) SetParent(v *Account) *AccountCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Account entity by IDs.
func (_c *AccountCreate) AddChildIDs(ids ...uuid.UUID) *AccountCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Account entity.
func (_c *AccountCreate) AddChildren(v ...*Account) *AccountCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_c *AccountCreate) Mutation() *AccountMutation {
	return _c.mutation
}

// Save creates the Account in the database.
func (_c *AccountCreate) Save(ctx context.Context) (*Account, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := account.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := account.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := account.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := account.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCreate) check() error {
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "createdBy", err: errors.New(`ent: missing required field "Account.createdBy"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Account.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updatedBy", err: errors.New(`ent: missing required field "Account.updatedBy"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Account.updatedAt"`)}
	}
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "Account.workspace_id"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Account.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := account.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Account.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Account.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Account.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := account.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Account.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Account.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := account.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Account.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Account.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := account.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Account.status": %w`, err)}
		}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "Account.creator"`)}
	}
	if len(_c.mutation.UpdaterIDs()) == 0 {
		return &ValidationError{Name: "updater", err: errors.New(`ent: missing required edge "Account.updater"`)}
	}
	return nil
}

func (_c *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.Account
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(account.FieldWorkspaceID, field.TypeUUID, value)
		_node.WorkspaceID = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(account.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(account.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(account.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(account.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(account.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.CreatorTable,
			Columns: []string{account.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   account.UpdaterTable,
			Columns: []string{account.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UpdatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.ParentTable,
			Columns: []string{account.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentId = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChildrenTable,
			Columns: []string{account.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.Account
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.Create().
//		SetCreatedBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCreate) OnConflict(opts ...sql.ConflictOption) *AccountUpsertOne {
	_c.conflict = opts
	return &AccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCreate) OnConflictColumns(columns ...string) *AccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertOne{
		create: _c,
	}
}

type (
	// AccountUpsertOne is the builder for "upsert"-ing
	//  one Account node.
	AccountUpsertOne struct {
		create *AccountCreate
	}

	// AccountUpsert is the "OnConflict" setter.
	AccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedBy sets the "createdBy" field.
func (u *AccountUpsert) SetCreatedBy(v uuid.UUID) *AccountUpsert {
	u.Set(account.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "createdBy" field to the value that was provided on create.
func (u *AccountUpsert) UpdateCreatedBy() *AccountUpsert {
	u.SetExcluded(account.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updatedBy" field.
func (u *AccountUpsert) SetUpdatedBy(v uuid.UUID) *AccountUpsert {
	u.Set(account.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updatedBy" field to the value that was provided on create.
func (u *AccountUpsert) UpdateUpdatedBy() *AccountUpsert {
	u.SetExcluded(account.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *AccountUpsert) SetUpdatedAt(v time.Time) *AccountUpsert {
	u.Set(account.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *AccountUpsert) UpdateUpdatedAt() *AccountUpsert {
	u.SetExcluded(account.FieldUpdatedAt)
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *AccountUpsert) SetWorkspaceID(v uuid.UUID) *AccountUpsert {
	u.Set(account.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *AccountUpsert) UpdateWorkspaceID() *AccountUpsert {
	u.SetExcluded(account.FieldWorkspaceID)
	return u
}

// SetCode sets the "code" field.
func (u *AccountUpsert) SetCode(v string) *AccountUpsert {
	u.Set(account.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *AccountUpsert) UpdateCode() *AccountUpsert {
	u.SetExcluded(account.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *AccountUpsert) SetName(v string) *AccountUpsert {
	u.Set(account.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpsert) UpdateName() *AccountUpsert {
	u.SetExcluded(account.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *AccountUpsert) SetDescription(v string) *AccountUpsert {
	u.Set(account.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountUpsert) UpdateDescription() *AccountUpsert {
	u.SetExcluded(account.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *AccountUpsert) ClearDescription() *AccountUpsert {
	u.SetNull(account.FieldDescription)
	return u
}

// SetType sets the "type" field.
func (u *AccountUpsert) SetType(v account.Type) *AccountUpsert {
	u.Set(account.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AccountUpsert) UpdateType() *AccountUpsert {
	u.SetExcluded(account.FieldType)
	return u
}

// SetCurrency sets the "currency" field.
func (u *AccountUpsert) SetCurrency(v string) *AccountUpsert {
	u.Set(account.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *AccountUpsert) UpdateCurrency() *AccountUpsert {
	u.SetExcluded(account.FieldCurrency)
	return u
}

// SetStatus sets the "status" field.
func (u *AccountUpsert) SetStatus(v account.Status) *AccountUpsert {
	u.Set(account.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountUpsert) UpdateStatus() *AccountUpsert {
	u.SetExcluded(account.FieldStatus)
	return u
}

// SetParentId sets the "parentId" field.
func (u *AccountUpsert) SetParentId(v uuid.UUID) *AccountUpsert {
	u.Set(account.FieldParentId, v)
	return u
}

// UpdateParentId sets the "parentId" field to the value that was provided on create.
func (u *AccountUpsert) UpdateParentId() *AccountUpsert {
	u.SetExcluded(account.FieldParentId)
	return u
}

// ClearParentId clears the value of the "parentId" field.
func (u *AccountUpsert) ClearParentId() *AccountUpsert {
	u.SetNull(account.FieldParentId)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(account.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountUpsertOne) UpdateNewValues() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(account.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(account.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountUpsertOne) Ignore() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertOne) DoNothing() *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreate.OnConflict
// documentation for more info.
func (u *AccountUpsertOne) Update(set func(*AccountUpsert)) *AccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "createdBy" field.
func (u *AccountUpsertOne) SetCreatedBy(v uuid.UUID) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "createdBy" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateCreatedBy() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updatedBy" field.
func (u *AccountUpsertOne) SetUpdatedBy(v uuid.UUID) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updatedBy" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateUpdatedBy() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *AccountUpsertOne) SetUpdatedAt(v time.Time) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateUpdatedAt() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *AccountUpsertOne) SetWorkspaceID(v uuid.UUID) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateWorkspaceID() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetCode sets the "code" field.
func (u *AccountUpsertOne) SetCode(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateCode() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *AccountUpsertOne) SetName(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateName() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *AccountUpsertOne) SetDescription(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateDescription() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AccountUpsertOne) ClearDescription() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.ClearDescription()
	})
}

// SetType sets the "type" field.
func (u *AccountUpsertOne) SetType(v account.Type) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateType() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateType()
	})
}

// SetCurrency sets the "currency" field.
func (u *AccountUpsertOne) SetCurrency(v string) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateCurrency() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *AccountUpsertOne) SetStatus(v account.Status) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateStatus() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateStatus()
	})
}

// SetParentId sets the "parentId" field.
func (u *AccountUpsertOne) SetParentId(v uuid.UUID) *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.SetParentId(v)
	})
}

// UpdateParentId sets the "parentId" field to the value that was provided on create.
func (u *AccountUpsertOne) UpdateParentId() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateParentId()
	})
}

// ClearParentId clears the value of the "parentId" field.
func (u *AccountUpsertOne) ClearParentId() *AccountUpsertOne {
	return u.Update(func(s *AccountUpsert) {
		s.ClearParentId()
	})
}

// Exec executes the query.
func (u *AccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AccountUpsertOne.ID is not supported by MySQL driver. Use AccountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
	conflict []sql.ConflictOption
}

// Save creates the Account entities in the database.
func (_c *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Account, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Account.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountUpsertBulk {
	_c.conflict = opts
	return &AccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountCreateBulk) OnConflictColumns(columns ...string) *AccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountUpsertBulk{
		create: _c,
	}
}

// AccountUpsertBulk is the builder for "upsert"-ing
// a bulk of Account nodes.
type AccountUpsertBulk struct {
	create *AccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(account.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountUpsertBulk) UpdateNewValues() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(account.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(account.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Account.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountUpsertBulk) Ignore() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountUpsertBulk) DoNothing() *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountCreateBulk.OnConflict
// documentation for more info.
func (u *AccountUpsertBulk) Update(set func(*AccountUpsert)) *AccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "createdBy" field.
func (u *AccountUpsertBulk) SetCreatedBy(v uuid.UUID) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "createdBy" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateCreatedBy() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updatedBy" field.
func (u *AccountUpsertBulk) SetUpdatedBy(v uuid.UUID) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updatedBy" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateUpdatedBy() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *AccountUpsertBulk) SetUpdatedAt(v time.Time) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateUpdatedAt() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *AccountUpsertBulk) SetWorkspaceID(v uuid.UUID) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateWorkspaceID() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetCode sets the "code" field.
func (u *AccountUpsertBulk) SetCode(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateCode() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *AccountUpsertBulk) SetName(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateName() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *AccountUpsertBulk) SetDescription(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateDescription() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AccountUpsertBulk) ClearDescription() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.ClearDescription()
	})
}

// SetType sets the "type" field.
func (u *AccountUpsertBulk) SetType(v account.Type) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateType() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateType()
	})
}

// SetCurrency sets the "currency" field.
func (u *AccountUpsertBulk) SetCurrency(v string) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateCurrency() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *AccountUpsertBulk) SetStatus(v account.Status) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateStatus() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateStatus()
	})
}

// SetParentId sets the "parentId" field.
func (u *AccountUpsertBulk) SetParentId(v uuid.UUID) *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.SetParentId(v)
	})
}

// UpdateParentId sets the "parentId" field to the value that was provided on create.
func (u *AccountUpsertBulk) UpdateParentId() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.UpdateParentId()
	})
}

// ClearParentId clears the value of the "parentId" field.
func (u *AccountUpsertBulk) ClearParentId() *AccountUpsertBulk {
	return u.Update(func(s *AccountUpsert) {
		s.ClearParentId()
	})
}

// Exec executes the query.
func (u *AccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
