// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kilip/omed/finance/ent/exchangerate"
	"github.com/shopspring/decimal"
)

// ExchangeRateCreate is the builder for creating a ExchangeRate entity.
type ExchangeRateCreate struct {
	config
	mutation *ExchangeRateMutation
	hooks    []Hook
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *ExchangeRateCreate) SetWorkspaceID(v uuid.UUID) *ExchangeRateCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetFromCurrency sets the "fromCurrency" field.
func (_c *ExchangeRateCreate) SetFromCurrency(v string) *ExchangeRateCreate {
	_c.mutation.SetFromCurrency(v)
	return _c
}

// SetToCurrency sets the "toCurrency" field.
func (_c *ExchangeRateCreate) SetToCurrency(v string) *ExchangeRateCreate {
	_c.mutation.SetToCurrency(v)
	return _c
}

// SetRate sets the "rate" field.
func (_c *ExchangeRateCreate) SetRate(v decimal.Decimal) *ExchangeRateCreate {
	_c.mutation.SetRate(v)
	return _c
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableRate(v *decimal.Decimal) *ExchangeRateCreate {
	if v != nil {
		_c.SetRate(*v)
	}
	return _c
}

// SetRateDate sets the "rateDate" field.
func (_c *ExchangeRateCreate) SetRateDate(v time.Time) *ExchangeRateCreate {
	_c.mutation.SetRateDate(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *ExchangeRateCreate) SetSource(v string) *ExchangeRateCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableSource(v *string) *ExchangeRateCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExchangeRateCreate) SetID(v uuid.UUID) *ExchangeRateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ExchangeRateCreate) SetNillableID(v *uuid.UUID) *ExchangeRateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ExchangeRateMutation object of the builder.
func (_c *ExchangeRateCreate) Mutation() *ExchangeRateMutation {
	return _c.mutation
}

// Save creates the ExchangeRate in the database.
func (_c *ExchangeRateCreate) Save(ctx context.Context) (*ExchangeRate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExchangeRateCreate) SaveX(ctx context.Context) *ExchangeRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeRateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeRateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExchangeRateCreate) defaults() {
	if _, ok := _c.mutation.Rate(); !ok {
		v := exchangerate.DefaultRate
		_c.mutation.SetRate(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := exchangerate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExchangeRateCreate) check() error {
	if _, ok := _c.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "ExchangeRate.workspace_id"`)}
	}
	if _, ok := _c.mutation.FromCurrency(); !ok {
		return &ValidationError{Name: "fromCurrency", err: errors.New(`ent: missing required field "ExchangeRate.fromCurrency"`)}
	}
	if v, ok := _c.mutation.FromCurrency(); ok {
		if err := exchangerate.FromCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "fromCurrency", err: fmt.Errorf(`ent: validator failed for field "ExchangeRate.fromCurrency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToCurrency(); !ok {
		return &ValidationError{Name: "toCurrency", err: errors.New(`ent: missing required field "ExchangeRate.toCurrency"`)}
	}
	if v, ok := _c.mutation.ToCurrency(); ok {
		if err := exchangerate.ToCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "toCurrency", err: fmt.Errorf(`ent: validator failed for field "ExchangeRate.toCurrency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "ExchangeRate.rate"`)}
	}
	if _, ok := _c.mutation.RateDate(); !ok {
		return &ValidationError{Name: "rateDate", err: errors.New(`ent: missing required field "ExchangeRate.rateDate"`)}
	}
	return nil
}

func (_c *ExchangeRateCreate) sqlSave(ctx context.Context) (*ExchangeRate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExchangeRateCreate) createSpec() (*ExchangeRate, *sqlgraph.CreateSpec) {
	var (
		_node = &ExchangeRate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exchangerate.Table, sqlgraph.NewFieldSpec(exchangerate.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.ExchangeRate
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.WorkspaceID(); ok {
		_spec.SetField(exchangerate.FieldWorkspaceID, field.TypeUUID, value)
		_node.WorkspaceID = value
	}
	if value, ok := _c.mutation.FromCurrency(); ok {
		_spec.SetField(exchangerate.FieldFromCurrency, field.TypeString, value)
		_node.FromCurrency = value
	}
	if value, ok := _c.mutation.ToCurrency(); ok {
		_spec.SetField(exchangerate.FieldToCurrency, field.TypeString, value)
		_node.ToCurrency = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(exchangerate.FieldRate, field.TypeOther, value)
		_node.Rate = value
	}
	if value, ok := _c.mutation.RateDate(); ok {
		_spec.SetField(exchangerate.FieldRateDate, field.TypeTime, value)
		_node.RateDate = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(exchangerate.FieldSource, field.TypeString, value)
		_node.Source = &value
	}
	return _node, _spec
}

// ExchangeRateCreateBulk is the builder for creating many ExchangeRate entities in bulk.
type ExchangeRateCreateBulk struct {
	config
	err      error
	builders []*ExchangeRateCreate
}

// Save creates the ExchangeRate entities in the database.
func (_c *ExchangeRateCreateBulk) Save(ctx context.Context) ([]*ExchangeRate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExchangeRate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExchangeRateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExchangeRateCreateBulk) SaveX(ctx context.Context) []*ExchangeRate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeRateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeRateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
