// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kilip/omed/finance/ent/entry"
	"github.com/kilip/omed/finance/ent/internal"
	"github.com/kilip/omed/finance/ent/period"
	"github.com/kilip/omed/finance/ent/predicate"
	"github.com/kilip/omed/finance/ent/user"
)

// PeriodUpdate is the builder for updating Period entities.
type PeriodUpdate struct {
	config
	hooks    []Hook
	mutation *PeriodMutation
}

// Where appends a list predicates to the PeriodUpdate builder.
func (_u *PeriodUpdate) Where(ps ...predicate.Period) *PeriodUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "createdBy" field.
func (_u *PeriodUpdate) SetCreatedBy(v uuid.UUID) *PeriodUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_u *PeriodUpdate) SetNillableCreatedBy(v *uuid.UUID) *PeriodUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *PeriodUpdate) SetUpdatedBy(v uuid.UUID) *PeriodUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *PeriodUpdate) SetNillableUpdatedBy(v *uuid.UUID) *PeriodUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *PeriodUpdate) SetUpdatedAt(v time.Time) *PeriodUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *PeriodUpdate) SetWorkspaceID(v uuid.UUID) *PeriodUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *PeriodUpdate) SetNillableWorkspaceID(v *uuid.UUID) *PeriodUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *PeriodUpdate) SetStartDate(v time.Time) *PeriodUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *PeriodUpdate) SetNillableStartDate(v *time.Time) *PeriodUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *PeriodUpdate) SetEndDate(v time.Time) *PeriodUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *PeriodUpdate) SetNillableEndDate(v *time.Time) *PeriodUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PeriodUpdate) SetStatus(v period.Status) *PeriodUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PeriodUpdate) SetNillableStatus(v *period.Status) *PeriodUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *PeriodUpdate) SetCreatorID(id uuid.UUID) *PeriodUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *PeriodUpdate) SetCreator(v *User) *PeriodUpdate {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *PeriodUpdate) SetUpdaterID(id uuid.UUID) *PeriodUpdate {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *PeriodUpdate) SetUpdater(v *User) *PeriodUpdate {
	return _u.SetUpdaterID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the Entry entity by IDs.
func (_u *PeriodUpdate) AddEntryIDs(ids ...uuid.UUID) *PeriodUpdate {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the Entry entity.
func (_u *PeriodUpdate) AddEntries(v ...*Entry) *PeriodUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// Mutation returns the PeriodMutation object of the builder.
func (_u *PeriodUpdate) Mutation() *PeriodMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *PeriodUpdate) ClearCreator() *PeriodUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *PeriodUpdate) ClearUpdater() *PeriodUpdate {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearEntries clears all "entries" edges to the Entry entity.
func (_u *PeriodUpdate) ClearEntries() *PeriodUpdate {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to Entry entities by IDs.
func (_u *PeriodUpdate) RemoveEntryIDs(ids ...uuid.UUID) *PeriodUpdate {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to Entry entities.
func (_u *PeriodUpdate) RemoveEntries(v ...*Entry) *PeriodUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PeriodUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PeriodUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PeriodUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PeriodUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PeriodUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := period.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PeriodUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := period.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Period.status": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Period.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Period.updater"`)
	}
	return nil
}

func (_u *PeriodUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(period.Table, period.Columns, sqlgraph.NewFieldSpec(period.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(period.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(period.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(period.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(period.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(period.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   period.CreatorTable,
			Columns: []string{period.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Period
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   period.CreatorTable,
			Columns: []string{period.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Period
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   period.UpdaterTable,
			Columns: []string{period.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Period
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   period.UpdaterTable,
			Columns: []string{period.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Period
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   period.EntriesTable,
			Columns: []string{period.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Entry
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   period.EntriesTable,
			Columns: []string{period.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Entry
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   period.EntriesTable,
			Columns: []string{period.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Entry
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Period
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{period.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PeriodUpdateOne is the builder for updating a single Period entity.
type PeriodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PeriodMutation
}

// SetCreatedBy sets the "createdBy" field.
func (_u *PeriodUpdateOne) SetCreatedBy(v uuid.UUID) *PeriodUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_u *PeriodUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *PeriodUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *PeriodUpdateOne) SetUpdatedBy(v uuid.UUID) *PeriodUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *PeriodUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *PeriodUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *PeriodUpdateOne) SetUpdatedAt(v time.Time) *PeriodUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *PeriodUpdateOne) SetWorkspaceID(v uuid.UUID) *PeriodUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *PeriodUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *PeriodUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *PeriodUpdateOne) SetStartDate(v time.Time) *PeriodUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *PeriodUpdateOne) SetNillableStartDate(v *time.Time) *PeriodUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *PeriodUpdateOne) SetEndDate(v time.Time) *PeriodUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *PeriodUpdateOne) SetNillableEndDate(v *time.Time) *PeriodUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PeriodUpdateOne) SetStatus(v period.Status) *PeriodUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PeriodUpdateOne) SetNillableStatus(v *period.Status) *PeriodUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *PeriodUpdateOne) SetCreatorID(id uuid.UUID) *PeriodUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *PeriodUpdateOne) SetCreator(v *User) *PeriodUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *PeriodUpdateOne) SetUpdaterID(id uuid.UUID) *PeriodUpdateOne {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *PeriodUpdateOne) SetUpdater(v *User) *PeriodUpdateOne {
	return _u.SetUpdaterID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the Entry entity by IDs.
func (_u *PeriodUpdateOne) AddEntryIDs(ids ...uuid.UUID) *PeriodUpdateOne {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the Entry entity.
func (_u *PeriodUpdateOne) AddEntries(v ...*Entry) *PeriodUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// Mutation returns the PeriodMutation object of the builder.
func (_u *PeriodUpdateOne) Mutation() *PeriodMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *PeriodUpdateOne) ClearCreator() *PeriodUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *PeriodUpdateOne) ClearUpdater() *PeriodUpdateOne {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearEntries clears all "entries" edges to the Entry entity.
func (_u *PeriodUpdateOne) ClearEntries() *PeriodUpdateOne {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to Entry entities by IDs.
func (_u *PeriodUpdateOne) RemoveEntryIDs(ids ...uuid.UUID) *PeriodUpdateOne {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to Entry entities.
func (_u *PeriodUpdateOne) RemoveEntries(v ...*Entry) *PeriodUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// Where appends a list predicates to the PeriodUpdate builder.
func (_u *PeriodUpdateOne) Where(ps ...predicate.Period) *PeriodUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PeriodUpdateOne) Select(field string, fields ...string) *PeriodUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Period entity.
func (_u *PeriodUpdateOne) Save(ctx context.Context) (*Period, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PeriodUpdateOne) SaveX(ctx context.Context) *Period {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PeriodUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PeriodUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PeriodUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := period.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PeriodUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := period.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Period.status": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Period.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Period.updater"`)
	}
	return nil
}

func (_u *PeriodUpdateOne) sqlSave(ctx context.Context) (_node *Period, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(period.Table, period.Columns, sqlgraph.NewFieldSpec(period.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Period.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, period.FieldID)
		for _, f := range fields {
			if !period.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != period.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(period.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(period.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(period.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(period.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(period.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   period.CreatorTable,
			Columns: []string{period.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Period
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   period.CreatorTable,
			Columns: []string{period.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Period
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   period.UpdaterTable,
			Columns: []string{period.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Period
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   period.UpdaterTable,
			Columns: []string{period.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Period
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   period.EntriesTable,
			Columns: []string{period.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Entry
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   period.EntriesTable,
			Columns: []string{period.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Entry
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   period.EntriesTable,
			Columns: []string{period.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Entry
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Period
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Period{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{period.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
