// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kilip/omed/finance/ent/account"
	"github.com/kilip/omed/finance/ent/entry"
	"github.com/kilip/omed/finance/ent/internal"
	"github.com/kilip/omed/finance/ent/posting"
	"github.com/kilip/omed/finance/ent/predicate"
	"github.com/shopspring/decimal"
)

// PostingUpdate is the builder for updating Posting entities.
type PostingUpdate struct {
	config
	hooks    []Hook
	mutation *PostingMutation
}

// Where appends a list predicates to the PostingUpdate builder.
func (_u *PostingUpdate) Where(ps ...predicate.Posting) *PostingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *PostingUpdate) SetWorkspaceID(v uuid.UUID) *PostingUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableWorkspaceID(v *uuid.UUID) *PostingUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetEntryId sets the "entryId" field.
func (_u *PostingUpdate) SetEntryId(v uuid.UUID) *PostingUpdate {
	_u.mutation.SetEntryId(v)
	return _u
}

// SetNillableEntryId sets the "entryId" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableEntryId(v *uuid.UUID) *PostingUpdate {
	if v != nil {
		_u.SetEntryId(*v)
	}
	return _u
}

// SetAccountId sets the "accountId" field.
func (_u *PostingUpdate) SetAccountId(v uuid.UUID) *PostingUpdate {
	_u.mutation.SetAccountId(v)
	return _u
}

// SetNillableAccountId sets the "accountId" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableAccountId(v *uuid.UUID) *PostingUpdate {
	if v != nil {
		_u.SetAccountId(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PostingUpdate) SetCurrency(v string) *PostingUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableCurrency(v *string) *PostingUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetDebitAmount sets the "debitAmount" field.
func (_u *PostingUpdate) SetDebitAmount(v decimal.Decimal) *PostingUpdate {
	_u.mutation.SetDebitAmount(v)
	return _u
}

// SetNillableDebitAmount sets the "debitAmount" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableDebitAmount(v *decimal.Decimal) *PostingUpdate {
	if v != nil {
		_u.SetDebitAmount(*v)
	}
	return _u
}

// SetCreditAmount sets the "creditAmount" field.
func (_u *PostingUpdate) SetCreditAmount(v decimal.Decimal) *PostingUpdate {
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "creditAmount" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableCreditAmount(v *decimal.Decimal) *PostingUpdate {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// SetBaseCurrency sets the "base_currency" field.
func (_u *PostingUpdate) SetBaseCurrency(v string) *PostingUpdate {
	_u.mutation.SetBaseCurrency(v)
	return _u
}

// SetNillableBaseCurrency sets the "base_currency" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableBaseCurrency(v *string) *PostingUpdate {
	if v != nil {
		_u.SetBaseCurrency(*v)
	}
	return _u
}

// SetBaseDebitAmount sets the "baseDebitAmount" field.
func (_u *PostingUpdate) SetBaseDebitAmount(v decimal.Decimal) *PostingUpdate {
	_u.mutation.SetBaseDebitAmount(v)
	return _u
}

// SetNillableBaseDebitAmount sets the "baseDebitAmount" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableBaseDebitAmount(v *decimal.Decimal) *PostingUpdate {
	if v != nil {
		_u.SetBaseDebitAmount(*v)
	}
	return _u
}

// SetBaseCreditAmount sets the "baseCreditAmount" field.
func (_u *PostingUpdate) SetBaseCreditAmount(v decimal.Decimal) *PostingUpdate {
	_u.mutation.SetBaseCreditAmount(v)
	return _u
}

// SetNillableBaseCreditAmount sets the "baseCreditAmount" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableBaseCreditAmount(v *decimal.Decimal) *PostingUpdate {
	if v != nil {
		_u.SetBaseCreditAmount(*v)
	}
	return _u
}

// SetExchangeRate sets the "exchangeRate" field.
func (_u *PostingUpdate) SetExchangeRate(v decimal.Decimal) *PostingUpdate {
	_u.mutation.SetExchangeRate(v)
	return _u
}

// SetNillableExchangeRate sets the "exchangeRate" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableExchangeRate(v *decimal.Decimal) *PostingUpdate {
	if v != nil {
		_u.SetExchangeRate(*v)
	}
	return _u
}

// SetMemo sets the "memo" field.
func (_u *PostingUpdate) SetMemo(v string) *PostingUpdate {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *PostingUpdate) SetNillableMemo(v *string) *PostingUpdate {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *PostingUpdate) ClearMemo() *PostingUpdate {
	_u.mutation.ClearMemo()
	return _u
}

// SetEntryID sets the "entry" edge to the Entry entity by ID.
func (_u *PostingUpdate) SetEntryID(id uuid.UUID) *PostingUpdate {
	_u.mutation.SetEntryID(id)
	return _u
}

// SetEntry sets the "entry" edge to the Entry entity.
func (_u *PostingUpdate) SetEntry(v *Entry) *PostingUpdate {
	return _u.SetEntryID(v.ID)
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *PostingUpdate) SetAccountID(id uuid.UUID) *PostingUpdate {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *PostingUpdate) SetAccount(v *Account) *PostingUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the PostingMutation object of the builder.
func (_u *PostingUpdate) Mutation() *PostingMutation {
	return _u.mutation
}

// ClearEntry clears the "entry" edge to the Entry entity.
func (_u *PostingUpdate) ClearEntry() *PostingUpdate {
	_u.mutation.ClearEntry()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *PostingUpdate) ClearAccount() *PostingUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostingUpdate) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := posting.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Posting.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseCurrency(); ok {
		if err := posting.BaseCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "base_currency", err: fmt.Errorf(`ent: validator failed for field "Posting.base_currency": %w`, err)}
		}
	}
	if _u.mutation.EntryCleared() && len(_u.mutation.EntryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Posting.entry"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Posting.account"`)
	}
	return nil
}

func (_u *PostingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(posting.Table, posting.Columns, sqlgraph.NewFieldSpec(posting.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(posting.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(posting.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.DebitAmount(); ok {
		_spec.SetField(posting.FieldDebitAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(posting.FieldCreditAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.BaseCurrency(); ok {
		_spec.SetField(posting.FieldBaseCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseDebitAmount(); ok {
		_spec.SetField(posting.FieldBaseDebitAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.BaseCreditAmount(); ok {
		_spec.SetField(posting.FieldBaseCreditAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.ExchangeRate(); ok {
		_spec.SetField(posting.FieldExchangeRate, field.TypeOther, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(posting.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(posting.FieldMemo, field.TypeString)
	}
	if _u.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posting.EntryTable,
			Columns: []string{posting.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Posting
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posting.EntryTable,
			Columns: []string{posting.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Posting
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posting.AccountTable,
			Columns: []string{posting.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Posting
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posting.AccountTable,
			Columns: []string{posting.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Posting
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Posting
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{posting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostingUpdateOne is the builder for updating a single Posting entity.
type PostingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostingMutation
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *PostingUpdateOne) SetWorkspaceID(v uuid.UUID) *PostingUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *PostingUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetEntryId sets the "entryId" field.
func (_u *PostingUpdateOne) SetEntryId(v uuid.UUID) *PostingUpdateOne {
	_u.mutation.SetEntryId(v)
	return _u
}

// SetNillableEntryId sets the "entryId" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableEntryId(v *uuid.UUID) *PostingUpdateOne {
	if v != nil {
		_u.SetEntryId(*v)
	}
	return _u
}

// SetAccountId sets the "accountId" field.
func (_u *PostingUpdateOne) SetAccountId(v uuid.UUID) *PostingUpdateOne {
	_u.mutation.SetAccountId(v)
	return _u
}

// SetNillableAccountId sets the "accountId" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableAccountId(v *uuid.UUID) *PostingUpdateOne {
	if v != nil {
		_u.SetAccountId(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PostingUpdateOne) SetCurrency(v string) *PostingUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableCurrency(v *string) *PostingUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetDebitAmount sets the "debitAmount" field.
func (_u *PostingUpdateOne) SetDebitAmount(v decimal.Decimal) *PostingUpdateOne {
	_u.mutation.SetDebitAmount(v)
	return _u
}

// SetNillableDebitAmount sets the "debitAmount" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableDebitAmount(v *decimal.Decimal) *PostingUpdateOne {
	if v != nil {
		_u.SetDebitAmount(*v)
	}
	return _u
}

// SetCreditAmount sets the "creditAmount" field.
func (_u *PostingUpdateOne) SetCreditAmount(v decimal.Decimal) *PostingUpdateOne {
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "creditAmount" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableCreditAmount(v *decimal.Decimal) *PostingUpdateOne {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// SetBaseCurrency sets the "base_currency" field.
func (_u *PostingUpdateOne) SetBaseCurrency(v string) *PostingUpdateOne {
	_u.mutation.SetBaseCurrency(v)
	return _u
}

// SetNillableBaseCurrency sets the "base_currency" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableBaseCurrency(v *string) *PostingUpdateOne {
	if v != nil {
		_u.SetBaseCurrency(*v)
	}
	return _u
}

// SetBaseDebitAmount sets the "baseDebitAmount" field.
func (_u *PostingUpdateOne) SetBaseDebitAmount(v decimal.Decimal) *PostingUpdateOne {
	_u.mutation.SetBaseDebitAmount(v)
	return _u
}

// SetNillableBaseDebitAmount sets the "baseDebitAmount" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableBaseDebitAmount(v *decimal.Decimal) *PostingUpdateOne {
	if v != nil {
		_u.SetBaseDebitAmount(*v)
	}
	return _u
}

// SetBaseCreditAmount sets the "baseCreditAmount" field.
func (_u *PostingUpdateOne) SetBaseCreditAmount(v decimal.Decimal) *PostingUpdateOne {
	_u.mutation.SetBaseCreditAmount(v)
	return _u
}

// SetNillableBaseCreditAmount sets the "baseCreditAmount" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableBaseCreditAmount(v *decimal.Decimal) *PostingUpdateOne {
	if v != nil {
		_u.SetBaseCreditAmount(*v)
	}
	return _u
}

// SetExchangeRate sets the "exchangeRate" field.
func (_u *PostingUpdateOne) SetExchangeRate(v decimal.Decimal) *PostingUpdateOne {
	_u.mutation.SetExchangeRate(v)
	return _u
}

// SetNillableExchangeRate sets the "exchangeRate" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableExchangeRate(v *decimal.Decimal) *PostingUpdateOne {
	if v != nil {
		_u.SetExchangeRate(*v)
	}
	return _u
}

// SetMemo sets the "memo" field.
func (_u *PostingUpdateOne) SetMemo(v string) *PostingUpdateOne {
	_u.mutation.SetMemo(v)
	return _u
}

// SetNillableMemo sets the "memo" field if the given value is not nil.
func (_u *PostingUpdateOne) SetNillableMemo(v *string) *PostingUpdateOne {
	if v != nil {
		_u.SetMemo(*v)
	}
	return _u
}

// ClearMemo clears the value of the "memo" field.
func (_u *PostingUpdateOne) ClearMemo() *PostingUpdateOne {
	_u.mutation.ClearMemo()
	return _u
}

// SetEntryID sets the "entry" edge to the Entry entity by ID.
func (_u *PostingUpdateOne) SetEntryID(id uuid.UUID) *PostingUpdateOne {
	_u.mutation.SetEntryID(id)
	return _u
}

// SetEntry sets the "entry" edge to the Entry entity.
func (_u *PostingUpdateOne) SetEntry(v *Entry) *PostingUpdateOne {
	return _u.SetEntryID(v.ID)
}

// SetAccountID sets the "account" edge to the Account entity by ID.
func (_u *PostingUpdateOne) SetAccountID(id uuid.UUID) *PostingUpdateOne {
	_u.mutation.SetAccountID(id)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *PostingUpdateOne) SetAccount(v *Account) *PostingUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the PostingMutation object of the builder.
func (_u *PostingUpdateOne) Mutation() *PostingMutation {
	return _u.mutation
}

// ClearEntry clears the "entry" edge to the Entry entity.
func (_u *PostingUpdateOne) ClearEntry() *PostingUpdateOne {
	_u.mutation.ClearEntry()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *PostingUpdateOne) ClearAccount() *PostingUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the PostingUpdate builder.
func (_u *PostingUpdateOne) Where(ps ...predicate.Posting) *PostingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostingUpdateOne) Select(field string, fields ...string) *PostingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Posting entity.
func (_u *PostingUpdateOne) Save(ctx context.Context) (*Posting, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostingUpdateOne) SaveX(ctx context.Context) *Posting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostingUpdateOne) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := posting.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Posting.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseCurrency(); ok {
		if err := posting.BaseCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "base_currency", err: fmt.Errorf(`ent: validator failed for field "Posting.base_currency": %w`, err)}
		}
	}
	if _u.mutation.EntryCleared() && len(_u.mutation.EntryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Posting.entry"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Posting.account"`)
	}
	return nil
}

func (_u *PostingUpdateOne) sqlSave(ctx context.Context) (_node *Posting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(posting.Table, posting.Columns, sqlgraph.NewFieldSpec(posting.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Posting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, posting.FieldID)
		for _, f := range fields {
			if !posting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != posting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(posting.FieldWorkspaceID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(posting.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.DebitAmount(); ok {
		_spec.SetField(posting.FieldDebitAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(posting.FieldCreditAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.BaseCurrency(); ok {
		_spec.SetField(posting.FieldBaseCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseDebitAmount(); ok {
		_spec.SetField(posting.FieldBaseDebitAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.BaseCreditAmount(); ok {
		_spec.SetField(posting.FieldBaseCreditAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.ExchangeRate(); ok {
		_spec.SetField(posting.FieldExchangeRate, field.TypeOther, value)
	}
	if value, ok := _u.mutation.Memo(); ok {
		_spec.SetField(posting.FieldMemo, field.TypeString, value)
	}
	if _u.mutation.MemoCleared() {
		_spec.ClearField(posting.FieldMemo, field.TypeString)
	}
	if _u.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posting.EntryTable,
			Columns: []string{posting.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Posting
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   posting.EntryTable,
			Columns: []string{posting.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Posting
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posting.AccountTable,
			Columns: []string{posting.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Posting
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   posting.AccountTable,
			Columns: []string{posting.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Posting
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Posting
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Posting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{posting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
