// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/kilip/omed/finance/ent/account"
	"github.com/kilip/omed/finance/ent/entry"
	"github.com/kilip/omed/finance/ent/period"
	"github.com/kilip/omed/finance/ent/schema"
	"github.com/kilip/omed/finance/ent/user"
	"github.com/kilip/omed/finance/ent/workspace"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountMixinFields1 := accountMixin[1].Fields()
	_ = accountMixinFields1
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreatedAt is the schema descriptor for createdAt field.
	accountDescCreatedAt := accountMixinFields1[1].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the createdAt field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updatedAt field.
	accountDescUpdatedAt := accountMixinFields1[3].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountDescCode is the schema descriptor for code field.
	accountDescCode := accountFields[0].Descriptor()
	// account.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	account.CodeValidator = accountDescCode.Validators[0].(func(string) error)
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[1].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = accountDescName.Validators[0].(func(string) error)
	// accountDescCurrency is the schema descriptor for currency field.
	accountDescCurrency := accountFields[4].Descriptor()
	// account.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	account.CurrencyValidator = accountDescCurrency.Validators[0].(func(string) error)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountMixinFields0[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	entryMixin := schema.Entry{}.Mixin()
	entryMixinFields0 := entryMixin[0].Fields()
	_ = entryMixinFields0
	entryMixinFields1 := entryMixin[1].Fields()
	_ = entryMixinFields1
	entryFields := schema.Entry{}.Fields()
	_ = entryFields
	// entryDescCreatedAt is the schema descriptor for createdAt field.
	entryDescCreatedAt := entryMixinFields1[1].Descriptor()
	// entry.DefaultCreatedAt holds the default value on creation for the createdAt field.
	entry.DefaultCreatedAt = entryDescCreatedAt.Default.(func() time.Time)
	// entryDescUpdatedAt is the schema descriptor for updatedAt field.
	entryDescUpdatedAt := entryMixinFields1[3].Descriptor()
	// entry.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	entry.DefaultUpdatedAt = entryDescUpdatedAt.Default.(func() time.Time)
	// entry.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	entry.UpdateDefaultUpdatedAt = entryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// entryDescID is the schema descriptor for id field.
	entryDescID := entryMixinFields0[0].Descriptor()
	// entry.DefaultID holds the default value on creation for the id field.
	entry.DefaultID = entryDescID.Default.(func() uuid.UUID)
	periodMixin := schema.Period{}.Mixin()
	periodMixinFields0 := periodMixin[0].Fields()
	_ = periodMixinFields0
	periodMixinFields1 := periodMixin[1].Fields()
	_ = periodMixinFields1
	periodFields := schema.Period{}.Fields()
	_ = periodFields
	// periodDescCreatedAt is the schema descriptor for createdAt field.
	periodDescCreatedAt := periodMixinFields1[1].Descriptor()
	// period.DefaultCreatedAt holds the default value on creation for the createdAt field.
	period.DefaultCreatedAt = periodDescCreatedAt.Default.(func() time.Time)
	// periodDescUpdatedAt is the schema descriptor for updatedAt field.
	periodDescUpdatedAt := periodMixinFields1[3].Descriptor()
	// period.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	period.DefaultUpdatedAt = periodDescUpdatedAt.Default.(func() time.Time)
	// period.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	period.UpdateDefaultUpdatedAt = periodDescUpdatedAt.UpdateDefault.(func() time.Time)
	// periodDescID is the schema descriptor for id field.
	periodDescID := periodMixinFields0[0].Descriptor()
	// period.DefaultID holds the default value on creation for the id field.
	period.DefaultID = periodDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for createdAt field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the createdAt field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescSyncedAt is the schema descriptor for syncedAt field.
	userDescSyncedAt := userFields[3].Descriptor()
	// user.DefaultSyncedAt holds the default value on creation for the syncedAt field.
	user.DefaultSyncedAt = userDescSyncedAt.Default.(func() time.Time)
	// user.UpdateDefaultSyncedAt holds the default value on update for the syncedAt field.
	user.UpdateDefaultSyncedAt = userDescSyncedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	workspaceMixin := schema.Workspace{}.Mixin()
	workspaceMixinFields0 := workspaceMixin[0].Fields()
	_ = workspaceMixinFields0
	workspaceFields := schema.Workspace{}.Fields()
	_ = workspaceFields
	// workspaceDescName is the schema descriptor for name field.
	workspaceDescName := workspaceFields[0].Descriptor()
	// workspace.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workspace.NameValidator = workspaceDescName.Validators[0].(func(string) error)
	// workspaceDescCreatedAt is the schema descriptor for createdAt field.
	workspaceDescCreatedAt := workspaceFields[1].Descriptor()
	// workspace.DefaultCreatedAt holds the default value on creation for the createdAt field.
	workspace.DefaultCreatedAt = workspaceDescCreatedAt.Default.(func() time.Time)
	// workspaceDescSyncedAt is the schema descriptor for syncedAt field.
	workspaceDescSyncedAt := workspaceFields[2].Descriptor()
	// workspace.DefaultSyncedAt holds the default value on creation for the syncedAt field.
	workspace.DefaultSyncedAt = workspaceDescSyncedAt.Default.(func() time.Time)
	// workspaceDescID is the schema descriptor for id field.
	workspaceDescID := workspaceMixinFields0[0].Descriptor()
	// workspace.DefaultID holds the default value on creation for the id field.
	workspace.DefaultID = workspaceDescID.Default.(func() uuid.UUID)
}
