/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Account
         * @description Create a new account based on authenticated user workspace
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Account Payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["model.Account"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["model.Account"];
                    };
                };
                /** @description Invalid request payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["http.ErrorResponse"];
                    };
                };
                /** @description Missing or invalid authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["http.ErrorResponse"];
                    };
                };
                /** @description Insufficient permission */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["http.ErrorResponse"];
                    };
                };
                /** @description Validation failed */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["http.ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["http.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "http.ErrorResponse": {
            /** @example field 'name' is required */
            detail?: string;
            /** @description field-level validation errors */
            errors?: {
                [key: string]: string;
            };
            /** @example /accounts */
            instance?: string;
            /** @example 400 */
            status?: number;
            /** @example Validation Failed */
            title?: string;
            /** @example a1b2c3d4 */
            trace_id?: string;
            /** @example https://omed.dev/errors/validation-failed */
            type?: string;
        };
        "model.Account": {
            code?: string;
            id?: string;
            name?: string;
            parentId?: string;
            type?: components["schemas"]["model.AccountType"];
        };
        /** @enum {string} */
        "model.AccountType": "asset" | "liability" | "equity" | "income" | "expense";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
