// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountColumns holds the columns for the "account" table.
	AccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "code", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"asset", "liability", "equity", "revenue", "expense"}},
		{Name: "currency", Type: field.TypeString, Size: 3},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "archived"}, Default: "active"},
		{Name: "created_by", Type: field.TypeUUID},
		{Name: "updated_by", Type: field.TypeUUID},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
	}
	// AccountTable holds the schema information for the "account" table.
	AccountTable = &schema.Table{
		Name:       "account",
		Columns:    AccountColumns,
		PrimaryKey: []*schema.Column{AccountColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "account_user_creator",
				Columns:    []*schema.Column{AccountColumns[10]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "account_user_updater",
				Columns:    []*schema.Column{AccountColumns[11]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "account_account_children",
				Columns:    []*schema.Column{AccountColumns[12]},
				RefColumns: []*schema.Column{AccountColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "account_workspace_id",
				Unique:  false,
				Columns: []*schema.Column{AccountColumns[3]},
			},
			{
				Name:    "account_workspace_id_code",
				Unique:  true,
				Columns: []*schema.Column{AccountColumns[3], AccountColumns[4]},
			},
		},
	}
	// EntryColumns holds the columns for the "entry" table.
	EntryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "entry_date", Type: field.TypeTime},
		{Name: "entry_type", Type: field.TypeEnum, Enums: []string{"normal", "opening_balance", "adjustment", "closing", "fx_adjustment"}, Default: "normal"},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "reference", Type: field.TypeString, Nullable: true},
		{Name: "created_by", Type: field.TypeUUID},
		{Name: "updated_by", Type: field.TypeUUID},
		{Name: "period_id", Type: field.TypeUUID},
	}
	// EntryTable holds the schema information for the "entry" table.
	EntryTable = &schema.Table{
		Name:       "entry",
		Columns:    EntryColumns,
		PrimaryKey: []*schema.Column{EntryColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "entry_user_creator",
				Columns:    []*schema.Column{EntryColumns[8]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "entry_user_updater",
				Columns:    []*schema.Column{EntryColumns[9]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "entry_period_entries",
				Columns:    []*schema.Column{EntryColumns[10]},
				RefColumns: []*schema.Column{PeriodColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "entry_workspace_id",
				Unique:  false,
				Columns: []*schema.Column{EntryColumns[3]},
			},
			{
				Name:    "entry_workspace_id_entry_date",
				Unique:  false,
				Columns: []*schema.Column{EntryColumns[3], EntryColumns[4]},
			},
		},
	}
	// PeriodColumns holds the columns for the "period" table.
	PeriodColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "workspace_id", Type: field.TypeUUID},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"open", "closed", "locked"}, Default: "open"},
		{Name: "created_by", Type: field.TypeUUID},
		{Name: "updated_by", Type: field.TypeUUID},
	}
	// PeriodTable holds the schema information for the "period" table.
	PeriodTable = &schema.Table{
		Name:       "period",
		Columns:    PeriodColumns,
		PrimaryKey: []*schema.Column{PeriodColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "period_user_creator",
				Columns:    []*schema.Column{PeriodColumns[7]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "period_user_updater",
				Columns:    []*schema.Column{PeriodColumns[8]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "period_workspace_id",
				Unique:  false,
				Columns: []*schema.Column{PeriodColumns[3]},
			},
		},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "avatar", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "synced_at", Type: field.TypeTime},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// WorkspaceColumns holds the columns for the "workspace" table.
	WorkspaceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "synced_at", Type: field.TypeTime},
	}
	// WorkspaceTable holds the schema information for the "workspace" table.
	WorkspaceTable = &schema.Table{
		Name:       "workspace",
		Columns:    WorkspaceColumns,
		PrimaryKey: []*schema.Column{WorkspaceColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountTable,
		EntryTable,
		PeriodTable,
		UserTable,
		WorkspaceTable,
	}
)

func init() {
	AccountTable.ForeignKeys[0].RefTable = UserTable
	AccountTable.ForeignKeys[1].RefTable = UserTable
	AccountTable.ForeignKeys[2].RefTable = AccountTable
	AccountTable.Annotation = &entsql.Annotation{
		Table: "account",
	}
	EntryTable.ForeignKeys[0].RefTable = UserTable
	EntryTable.ForeignKeys[1].RefTable = UserTable
	EntryTable.ForeignKeys[2].RefTable = PeriodTable
	EntryTable.Annotation = &entsql.Annotation{
		Table: "entry",
	}
	PeriodTable.ForeignKeys[0].RefTable = UserTable
	PeriodTable.ForeignKeys[1].RefTable = UserTable
	PeriodTable.Annotation = &entsql.Annotation{
		Table: "period",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
	WorkspaceTable.Annotation = &entsql.Annotation{
		Table: "workspace",
	}
}
