name = "auth"
main = "src/index.ts"
compatibility_date = "2026-09-28"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "auth.itstoni.com", custom_domain = true }
]

[vars]
AUTH_BASE_URL = "https://auth.itstoni.com"
AUTH_BASE_PATH = ""
AUTH_TRUSTED_ORIGINS = "https://omed.itstoni.com https://acc.itstoni.com https://blog.itstoni.com"
