/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available accounts
         * @description List available accounts
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Account Filter */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["github_com_kilip_omed_finance_internal_model.AccountFilter"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_kilip_omed_finance_internal_model.Envelope-github_com_kilip_omed_finance_internal_model_Account"];
                    };
                };
                /** @description Invalid request payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
                /** @description Missing or invalid authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
                /** @description Insufficient permission */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
                /** @description Validation failed */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create Account
         * @description Create a new account based on authenticated user workspace
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Account Payload */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["github_com_kilip_omed_finance_internal_model.Account"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_kilip_omed_finance_internal_model.Envelope-github_com_kilip_omed_finance_internal_model_Account"];
                    };
                };
                /** @description Invalid request payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
                /** @description Missing or invalid authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
                /** @description Insufficient permission */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
                /** @description Validation failed */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Check finance health
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_kilip_omed_finance_internal_model.Envelope-internal_delivery_http_PingResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_delivery_http.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_kilip_omed_finance_internal_delivery_http.ErrorResponse": {
            /** @example field 'name' is required */
            detail?: string;
            /** @description field-level validation errors */
            errors?: {
                [key: string]: string;
            };
            /** @example /accounts */
            instance?: string;
            /** @example 400 */
            status?: number;
            /** @example Validation Failed */
            title?: string;
            /** @example a1b2c3d4 */
            trace_id?: string;
            /** @example https://omed.dev/errors/validation-failed */
            type?: string;
        };
        "github_com_kilip_omed_finance_internal_delivery_http.PingResponse": {
            databaseStatus?: string;
            user?: components["schemas"]["github_com_kilip_omed_finance_internal_model.AuthenticatedUser"];
        };
        "github_com_kilip_omed_finance_internal_model.Account": {
            code?: string;
            createdAt?: string;
            createdBy?: string;
            currency?: string;
            detailType?: components["schemas"]["github_com_kilip_omed_finance_internal_model.AccountDetailType"];
            id?: string;
            name?: string;
            normalBalance?: components["schemas"]["github_com_kilip_omed_finance_internal_model.AccountNormalBalance"];
            parentId?: string;
            type?: components["schemas"]["github_com_kilip_omed_finance_internal_model.AccountType"];
            updatedAt?: string;
            updatedBy?: string;
        };
        /** @enum {string} */
        "github_com_kilip_omed_finance_internal_model.AccountDetailType": "cash" | "bank" | "ewallet" | "credit-card" | "payable" | "receivable";
        "github_com_kilip_omed_finance_internal_model.AccountFilter": {
            parentID?: string;
            type?: components["schemas"]["github_com_kilip_omed_finance_internal_model.AccountType"];
        };
        /** @enum {string} */
        "github_com_kilip_omed_finance_internal_model.AccountNormalBalance": "debit" | "credit";
        /** @enum {string} */
        "github_com_kilip_omed_finance_internal_model.AccountType": "asset" | "liability" | "equity" | "income" | "expense";
        "github_com_kilip_omed_finance_internal_model.AuthenticatedUser": {
            activeOrganizationRole?: string[];
            activeTeamId?: string;
            activeTeamName?: string;
            avatar?: string;
            id?: string;
            name?: string;
            role?: string[];
        };
        "github_com_kilip_omed_finance_internal_model.Cursor": {
            has_more?: boolean;
            next?: string;
            prev?: string;
        };
        "github_com_kilip_omed_finance_internal_model.Envelope-github_com_kilip_omed_finance_internal_delivery_http_PingResponse": {
            data?: components["schemas"]["github_com_kilip_omed_finance_internal_delivery_http.PingResponse"];
            error?: components["schemas"]["github_com_kilip_omed_finance_internal_model.ErrorInfo"];
            meta?: components["schemas"]["github_com_kilip_omed_finance_internal_model.Meta"];
            success?: boolean;
        };
        "github_com_kilip_omed_finance_internal_model.Envelope-github_com_kilip_omed_finance_internal_model_Account": {
            data?: components["schemas"]["github_com_kilip_omed_finance_internal_model.Account"];
            error?: components["schemas"]["github_com_kilip_omed_finance_internal_model.ErrorInfo"];
            meta?: components["schemas"]["github_com_kilip_omed_finance_internal_model.Meta"];
            success?: boolean;
        };
        "github_com_kilip_omed_finance_internal_model.Envelope-internal_delivery_http_PingResponse": {
            data?: components["schemas"]["internal_delivery_http.PingResponse"];
            error?: components["schemas"]["github_com_kilip_omed_finance_internal_model.ErrorInfo"];
            meta?: components["schemas"]["github_com_kilip_omed_finance_internal_model.Meta"];
            success?: boolean;
        };
        "github_com_kilip_omed_finance_internal_model.ErrorInfo": {
            code?: string;
            details?: unknown;
            message?: string;
        };
        "github_com_kilip_omed_finance_internal_model.Meta": {
            cursor?: components["schemas"]["github_com_kilip_omed_finance_internal_model.Cursor"];
            requestId?: string;
            timestamp?: string;
        };
        "internal_delivery_http.ErrorResponse": {
            /** @example field 'name' is required */
            detail?: string;
            /** @description field-level validation errors */
            errors?: {
                [key: string]: string;
            };
            /** @example /accounts */
            instance?: string;
            /** @example 400 */
            status?: number;
            /** @example Validation Failed */
            title?: string;
            /** @example a1b2c3d4 */
            trace_id?: string;
            /** @example https://omed.dev/errors/validation-failed */
            type?: string;
        };
        "internal_delivery_http.PingResponse": {
            databaseStatus?: string;
            user?: components["schemas"]["github_com_kilip_omed_finance_internal_model.AuthenticatedUser"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
