package core

import "errors"

var (
	ErrInvalidID                = errors.New("INVALID_ID_FORMAT")
	ErrGenerateID               = errors.New("GENERATE_ID_FAILED")
	ErrItemNotFound             = errors.New("ITEM_NOT_FOUND")
	ErrUnimplemented            = errors.New("NOT_IMPLEMENTED")
	ErrInvalidDateRange         = errors.New("INVALID_DATE_RANGE")
	ErrPeriodOverlap            = errors.New("PERIOD_OVERLAP")
	ErrInvalidStatusTransition  = errors.New("INVALID_STATUS_TRANSITION")
	ErrUnbalancedEntry          = errors.New("UNBALANCED_ENTRY")
	ErrMinPostingsCount         = errors.New("MIN_POSTINGS_COUNT")
	ErrPeriodClosed             = errors.New("PERIOD_CLOSED")
	ErrInactiveAccount          = errors.New("INACTIVE_ACCOUNT")
	ErrSameCurrencyNotAllowed   = errors.New("SAME_CURRENCY_NOT_ALLOWED")
	ErrInvalidExchangeRate      = errors.New("INVALID_EXCHANGE_RATE")
	ErrAccountsNotEmpty         = errors.New("ACCOUNTS_NOT_EMPTY")
	ErrEntriesNotEmpty          = errors.New("ENTRIES_NOT_EMPTY")
	ErrInvalidFileType          = errors.New("INVALID_FILE_TYPE")
	ErrFileTooLarge             = errors.New("FILE_TOO_LARGE")
	ErrAttachmentNotPending     = errors.New("ATTACHMENT_NOT_PENDING")
	ErrAttachmentObjectNotFound = errors.New("ATTACHMENT_OBJECT_NOT_FOUND")
	ErrPeriodLocked             = errors.New("PERIOD_LOCKED")
	ErrForbidden                = errors.New("FORBIDDEN")
	ErrInvalidAccountType       = errors.New("INVALID_ACCOUNT_TYPE")
	ErrMissingAccountMapping    = errors.New("MISSING_ACCOUNT_MAPPING")
	ErrContactInUse             = errors.New("CONTACT_IN_USE")
	ErrTaxRateInUse             = errors.New("TAX_RATE_IN_USE")
	ErrInvalidTaxRate           = errors.New("INVALID_TAX_RATE")
	ErrInvoiceNotDraft          = errors.New("INVOICE_NOT_DRAFT")
	ErrInvoiceNoLines           = errors.New("INVOICE_NO_LINES")
	ErrContactKindMismatch      = errors.New("CONTACT_KIND_MISMATCH")
	ErrTaxKindMismatch          = errors.New("TAX_KIND_MISMATCH")
	ErrInvoiceHasPayments       = errors.New("INVOICE_HAS_PAYMENTS")
	ErrInvoiceAlreadyVoid       = errors.New("INVOICE_ALREADY_VOID")
	ErrInvoiceNotIssued         = errors.New("INVOICE_NOT_ISSUED")
	ErrEntryLinked              = errors.New("ENTRY_LINKED")
	ErrOverpayment              = errors.New("OVERPAYMENT")
	ErrPaymentMismatch          = errors.New("PAYMENT_MISMATCH")
	ErrCurrencyMismatch         = errors.New("CURRENCY_MISMATCH")
	ErrPaymentAlreadyVoid       = errors.New("PAYMENT_ALREADY_VOID")
	ErrPaymentNotPosted         = errors.New("PAYMENT_NOT_POSTED")
	ErrDuplicateReference       = errors.New("DUPLICATE_REFERENCE")
	ErrInvoiceNotSendable       = errors.New("INVOICE_NOT_SENDABLE")
	ErrExchangeRateMissing      = errors.New("EXCHANGE_RATE_MISSING")
)
