// Code generated by ent, DO NOT EDIT.

package exchangerate

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const (
	// Label holds the string label denoting the exchangerate type in the database.
	Label = "exchange_rate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWorkspaceID holds the string denoting the workspace_id field in the database.
	FieldWorkspaceID = "workspace_id"
	// FieldFromCurrency holds the string denoting the fromcurrency field in the database.
	FieldFromCurrency = "from_currency"
	// FieldToCurrency holds the string denoting the tocurrency field in the database.
	FieldToCurrency = "to_currency"
	// FieldRate holds the string denoting the rate field in the database.
	FieldRate = "rate"
	// FieldRateDate holds the string denoting the ratedate field in the database.
	FieldRateDate = "rate_date"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// Table holds the table name of the exchangerate in the database.
	Table = "exchange_rate"
)

// Columns holds all SQL columns for exchangerate fields.
var Columns = []string{
	FieldID,
	FieldWorkspaceID,
	FieldFromCurrency,
	FieldToCurrency,
	FieldRate,
	FieldRateDate,
	FieldSource,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FromCurrencyValidator is a validator for the "fromCurrency" field. It is called by the builders before save.
	FromCurrencyValidator func(string) error
	// ToCurrencyValidator is a validator for the "toCurrency" field. It is called by the builders before save.
	ToCurrencyValidator func(string) error
	// DefaultRate holds the default value on creation for the "rate" field.
	DefaultRate decimal.Decimal
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ExchangeRate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWorkspaceID orders the results by the workspace_id field.
func ByWorkspaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspaceID, opts...).ToFunc()
}

// ByFromCurrency orders the results by the fromCurrency field.
func ByFromCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromCurrency, opts...).ToFunc()
}

// ByToCurrency orders the results by the toCurrency field.
func ByToCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToCurrency, opts...).ToFunc()
}

// ByRate orders the results by the rate field.
func ByRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRate, opts...).ToFunc()
}

// ByRateDate orders the results by the rateDate field.
func ByRateDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateDate, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}
