// Code generated by ent, DO NOT EDIT.

package posting

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/kilip/omed/finance/ent/internal"
	"github.com/kilip/omed/finance/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldLTE(FieldID, id))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldWorkspaceID, v))
}

// EntryId applies equality check predicate on the "entryId" field. It's identical to EntryIdEQ.
func EntryId(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldEntryId, v))
}

// AccountId applies equality check predicate on the "accountId" field. It's identical to AccountIdEQ.
func AccountId(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldAccountId, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldCurrency, v))
}

// DebitAmount applies equality check predicate on the "debitAmount" field. It's identical to DebitAmountEQ.
func DebitAmount(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldDebitAmount, v))
}

// CreditAmount applies equality check predicate on the "creditAmount" field. It's identical to CreditAmountEQ.
func CreditAmount(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldCreditAmount, v))
}

// BaseCurrency applies equality check predicate on the "base_currency" field. It's identical to BaseCurrencyEQ.
func BaseCurrency(v string) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldBaseCurrency, v))
}

// BaseDebitAmount applies equality check predicate on the "baseDebitAmount" field. It's identical to BaseDebitAmountEQ.
func BaseDebitAmount(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldBaseDebitAmount, v))
}

// BaseCreditAmount applies equality check predicate on the "baseCreditAmount" field. It's identical to BaseCreditAmountEQ.
func BaseCreditAmount(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldBaseCreditAmount, v))
}

// ExchangeRate applies equality check predicate on the "exchangeRate" field. It's identical to ExchangeRateEQ.
func ExchangeRate(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldExchangeRate, v))
}

// Memo applies equality check predicate on the "memo" field. It's identical to MemoEQ.
func Memo(v string) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldMemo, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDGT applies the GT predicate on the "workspace_id" field.
func WorkspaceIDGT(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldGT(FieldWorkspaceID, v))
}

// WorkspaceIDGTE applies the GTE predicate on the "workspace_id" field.
func WorkspaceIDGTE(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldGTE(FieldWorkspaceID, v))
}

// WorkspaceIDLT applies the LT predicate on the "workspace_id" field.
func WorkspaceIDLT(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldLT(FieldWorkspaceID, v))
}

// WorkspaceIDLTE applies the LTE predicate on the "workspace_id" field.
func WorkspaceIDLTE(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldLTE(FieldWorkspaceID, v))
}

// EntryIdEQ applies the EQ predicate on the "entryId" field.
func EntryIdEQ(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldEntryId, v))
}

// EntryIdNEQ applies the NEQ predicate on the "entryId" field.
func EntryIdNEQ(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldEntryId, v))
}

// EntryIdIn applies the In predicate on the "entryId" field.
func EntryIdIn(vs ...uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldEntryId, vs...))
}

// EntryIdNotIn applies the NotIn predicate on the "entryId" field.
func EntryIdNotIn(vs ...uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldEntryId, vs...))
}

// AccountIdEQ applies the EQ predicate on the "accountId" field.
func AccountIdEQ(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldAccountId, v))
}

// AccountIdNEQ applies the NEQ predicate on the "accountId" field.
func AccountIdNEQ(v uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldAccountId, v))
}

// AccountIdIn applies the In predicate on the "accountId" field.
func AccountIdIn(vs ...uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldAccountId, vs...))
}

// AccountIdNotIn applies the NotIn predicate on the "accountId" field.
func AccountIdNotIn(vs ...uuid.UUID) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldAccountId, vs...))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Posting {
	return predicate.Posting(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Posting {
	return predicate.Posting(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Posting {
	return predicate.Posting(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Posting {
	return predicate.Posting(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Posting {
	return predicate.Posting(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Posting {
	return predicate.Posting(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Posting {
	return predicate.Posting(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Posting {
	return predicate.Posting(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Posting {
	return predicate.Posting(sql.FieldContainsFold(FieldCurrency, v))
}

// DebitAmountEQ applies the EQ predicate on the "debitAmount" field.
func DebitAmountEQ(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldDebitAmount, v))
}

// DebitAmountNEQ applies the NEQ predicate on the "debitAmount" field.
func DebitAmountNEQ(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldDebitAmount, v))
}

// DebitAmountIn applies the In predicate on the "debitAmount" field.
func DebitAmountIn(vs ...decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldDebitAmount, vs...))
}

// DebitAmountNotIn applies the NotIn predicate on the "debitAmount" field.
func DebitAmountNotIn(vs ...decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldDebitAmount, vs...))
}

// DebitAmountGT applies the GT predicate on the "debitAmount" field.
func DebitAmountGT(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldGT(FieldDebitAmount, v))
}

// DebitAmountGTE applies the GTE predicate on the "debitAmount" field.
func DebitAmountGTE(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldGTE(FieldDebitAmount, v))
}

// DebitAmountLT applies the LT predicate on the "debitAmount" field.
func DebitAmountLT(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldLT(FieldDebitAmount, v))
}

// DebitAmountLTE applies the LTE predicate on the "debitAmount" field.
func DebitAmountLTE(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldLTE(FieldDebitAmount, v))
}

// CreditAmountEQ applies the EQ predicate on the "creditAmount" field.
func CreditAmountEQ(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldCreditAmount, v))
}

// CreditAmountNEQ applies the NEQ predicate on the "creditAmount" field.
func CreditAmountNEQ(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldCreditAmount, v))
}

// CreditAmountIn applies the In predicate on the "creditAmount" field.
func CreditAmountIn(vs ...decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldCreditAmount, vs...))
}

// CreditAmountNotIn applies the NotIn predicate on the "creditAmount" field.
func CreditAmountNotIn(vs ...decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldCreditAmount, vs...))
}

// CreditAmountGT applies the GT predicate on the "creditAmount" field.
func CreditAmountGT(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldGT(FieldCreditAmount, v))
}

// CreditAmountGTE applies the GTE predicate on the "creditAmount" field.
func CreditAmountGTE(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldGTE(FieldCreditAmount, v))
}

// CreditAmountLT applies the LT predicate on the "creditAmount" field.
func CreditAmountLT(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldLT(FieldCreditAmount, v))
}

// CreditAmountLTE applies the LTE predicate on the "creditAmount" field.
func CreditAmountLTE(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldLTE(FieldCreditAmount, v))
}

// BaseCurrencyEQ applies the EQ predicate on the "base_currency" field.
func BaseCurrencyEQ(v string) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldBaseCurrency, v))
}

// BaseCurrencyNEQ applies the NEQ predicate on the "base_currency" field.
func BaseCurrencyNEQ(v string) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldBaseCurrency, v))
}

// BaseCurrencyIn applies the In predicate on the "base_currency" field.
func BaseCurrencyIn(vs ...string) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldBaseCurrency, vs...))
}

// BaseCurrencyNotIn applies the NotIn predicate on the "base_currency" field.
func BaseCurrencyNotIn(vs ...string) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldBaseCurrency, vs...))
}

// BaseCurrencyGT applies the GT predicate on the "base_currency" field.
func BaseCurrencyGT(v string) predicate.Posting {
	return predicate.Posting(sql.FieldGT(FieldBaseCurrency, v))
}

// BaseCurrencyGTE applies the GTE predicate on the "base_currency" field.
func BaseCurrencyGTE(v string) predicate.Posting {
	return predicate.Posting(sql.FieldGTE(FieldBaseCurrency, v))
}

// BaseCurrencyLT applies the LT predicate on the "base_currency" field.
func BaseCurrencyLT(v string) predicate.Posting {
	return predicate.Posting(sql.FieldLT(FieldBaseCurrency, v))
}

// BaseCurrencyLTE applies the LTE predicate on the "base_currency" field.
func BaseCurrencyLTE(v string) predicate.Posting {
	return predicate.Posting(sql.FieldLTE(FieldBaseCurrency, v))
}

// BaseCurrencyContains applies the Contains predicate on the "base_currency" field.
func BaseCurrencyContains(v string) predicate.Posting {
	return predicate.Posting(sql.FieldContains(FieldBaseCurrency, v))
}

// BaseCurrencyHasPrefix applies the HasPrefix predicate on the "base_currency" field.
func BaseCurrencyHasPrefix(v string) predicate.Posting {
	return predicate.Posting(sql.FieldHasPrefix(FieldBaseCurrency, v))
}

// BaseCurrencyHasSuffix applies the HasSuffix predicate on the "base_currency" field.
func BaseCurrencyHasSuffix(v string) predicate.Posting {
	return predicate.Posting(sql.FieldHasSuffix(FieldBaseCurrency, v))
}

// BaseCurrencyEqualFold applies the EqualFold predicate on the "base_currency" field.
func BaseCurrencyEqualFold(v string) predicate.Posting {
	return predicate.Posting(sql.FieldEqualFold(FieldBaseCurrency, v))
}

// BaseCurrencyContainsFold applies the ContainsFold predicate on the "base_currency" field.
func BaseCurrencyContainsFold(v string) predicate.Posting {
	return predicate.Posting(sql.FieldContainsFold(FieldBaseCurrency, v))
}

// BaseDebitAmountEQ applies the EQ predicate on the "baseDebitAmount" field.
func BaseDebitAmountEQ(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldBaseDebitAmount, v))
}

// BaseDebitAmountNEQ applies the NEQ predicate on the "baseDebitAmount" field.
func BaseDebitAmountNEQ(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldBaseDebitAmount, v))
}

// BaseDebitAmountIn applies the In predicate on the "baseDebitAmount" field.
func BaseDebitAmountIn(vs ...decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldBaseDebitAmount, vs...))
}

// BaseDebitAmountNotIn applies the NotIn predicate on the "baseDebitAmount" field.
func BaseDebitAmountNotIn(vs ...decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldBaseDebitAmount, vs...))
}

// BaseDebitAmountGT applies the GT predicate on the "baseDebitAmount" field.
func BaseDebitAmountGT(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldGT(FieldBaseDebitAmount, v))
}

// BaseDebitAmountGTE applies the GTE predicate on the "baseDebitAmount" field.
func BaseDebitAmountGTE(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldGTE(FieldBaseDebitAmount, v))
}

// BaseDebitAmountLT applies the LT predicate on the "baseDebitAmount" field.
func BaseDebitAmountLT(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldLT(FieldBaseDebitAmount, v))
}

// BaseDebitAmountLTE applies the LTE predicate on the "baseDebitAmount" field.
func BaseDebitAmountLTE(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldLTE(FieldBaseDebitAmount, v))
}

// BaseCreditAmountEQ applies the EQ predicate on the "baseCreditAmount" field.
func BaseCreditAmountEQ(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldBaseCreditAmount, v))
}

// BaseCreditAmountNEQ applies the NEQ predicate on the "baseCreditAmount" field.
func BaseCreditAmountNEQ(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldBaseCreditAmount, v))
}

// BaseCreditAmountIn applies the In predicate on the "baseCreditAmount" field.
func BaseCreditAmountIn(vs ...decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldBaseCreditAmount, vs...))
}

// BaseCreditAmountNotIn applies the NotIn predicate on the "baseCreditAmount" field.
func BaseCreditAmountNotIn(vs ...decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldBaseCreditAmount, vs...))
}

// BaseCreditAmountGT applies the GT predicate on the "baseCreditAmount" field.
func BaseCreditAmountGT(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldGT(FieldBaseCreditAmount, v))
}

// BaseCreditAmountGTE applies the GTE predicate on the "baseCreditAmount" field.
func BaseCreditAmountGTE(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldGTE(FieldBaseCreditAmount, v))
}

// BaseCreditAmountLT applies the LT predicate on the "baseCreditAmount" field.
func BaseCreditAmountLT(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldLT(FieldBaseCreditAmount, v))
}

// BaseCreditAmountLTE applies the LTE predicate on the "baseCreditAmount" field.
func BaseCreditAmountLTE(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldLTE(FieldBaseCreditAmount, v))
}

// ExchangeRateEQ applies the EQ predicate on the "exchangeRate" field.
func ExchangeRateEQ(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldExchangeRate, v))
}

// ExchangeRateNEQ applies the NEQ predicate on the "exchangeRate" field.
func ExchangeRateNEQ(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldExchangeRate, v))
}

// ExchangeRateIn applies the In predicate on the "exchangeRate" field.
func ExchangeRateIn(vs ...decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldExchangeRate, vs...))
}

// ExchangeRateNotIn applies the NotIn predicate on the "exchangeRate" field.
func ExchangeRateNotIn(vs ...decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldExchangeRate, vs...))
}

// ExchangeRateGT applies the GT predicate on the "exchangeRate" field.
func ExchangeRateGT(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldGT(FieldExchangeRate, v))
}

// ExchangeRateGTE applies the GTE predicate on the "exchangeRate" field.
func ExchangeRateGTE(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldGTE(FieldExchangeRate, v))
}

// ExchangeRateLT applies the LT predicate on the "exchangeRate" field.
func ExchangeRateLT(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldLT(FieldExchangeRate, v))
}

// ExchangeRateLTE applies the LTE predicate on the "exchangeRate" field.
func ExchangeRateLTE(v decimal.Decimal) predicate.Posting {
	return predicate.Posting(sql.FieldLTE(FieldExchangeRate, v))
}

// MemoEQ applies the EQ predicate on the "memo" field.
func MemoEQ(v string) predicate.Posting {
	return predicate.Posting(sql.FieldEQ(FieldMemo, v))
}

// MemoNEQ applies the NEQ predicate on the "memo" field.
func MemoNEQ(v string) predicate.Posting {
	return predicate.Posting(sql.FieldNEQ(FieldMemo, v))
}

// MemoIn applies the In predicate on the "memo" field.
func MemoIn(vs ...string) predicate.Posting {
	return predicate.Posting(sql.FieldIn(FieldMemo, vs...))
}

// MemoNotIn applies the NotIn predicate on the "memo" field.
func MemoNotIn(vs ...string) predicate.Posting {
	return predicate.Posting(sql.FieldNotIn(FieldMemo, vs...))
}

// MemoGT applies the GT predicate on the "memo" field.
func MemoGT(v string) predicate.Posting {
	return predicate.Posting(sql.FieldGT(FieldMemo, v))
}

// MemoGTE applies the GTE predicate on the "memo" field.
func MemoGTE(v string) predicate.Posting {
	return predicate.Posting(sql.FieldGTE(FieldMemo, v))
}

// MemoLT applies the LT predicate on the "memo" field.
func MemoLT(v string) predicate.Posting {
	return predicate.Posting(sql.FieldLT(FieldMemo, v))
}

// MemoLTE applies the LTE predicate on the "memo" field.
func MemoLTE(v string) predicate.Posting {
	return predicate.Posting(sql.FieldLTE(FieldMemo, v))
}

// MemoContains applies the Contains predicate on the "memo" field.
func MemoContains(v string) predicate.Posting {
	return predicate.Posting(sql.FieldContains(FieldMemo, v))
}

// MemoHasPrefix applies the HasPrefix predicate on the "memo" field.
func MemoHasPrefix(v string) predicate.Posting {
	return predicate.Posting(sql.FieldHasPrefix(FieldMemo, v))
}

// MemoHasSuffix applies the HasSuffix predicate on the "memo" field.
func MemoHasSuffix(v string) predicate.Posting {
	return predicate.Posting(sql.FieldHasSuffix(FieldMemo, v))
}

// MemoIsNil applies the IsNil predicate on the "memo" field.
func MemoIsNil() predicate.Posting {
	return predicate.Posting(sql.FieldIsNull(FieldMemo))
}

// MemoNotNil applies the NotNil predicate on the "memo" field.
func MemoNotNil() predicate.Posting {
	return predicate.Posting(sql.FieldNotNull(FieldMemo))
}

// MemoEqualFold applies the EqualFold predicate on the "memo" field.
func MemoEqualFold(v string) predicate.Posting {
	return predicate.Posting(sql.FieldEqualFold(FieldMemo, v))
}

// MemoContainsFold applies the ContainsFold predicate on the "memo" field.
func MemoContainsFold(v string) predicate.Posting {
	return predicate.Posting(sql.FieldContainsFold(FieldMemo, v))
}

// HasEntry applies the HasEdge predicate on the "entry" edge.
func HasEntry() predicate.Posting {
	return predicate.Posting(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EntryTable, EntryColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Entry
		step.Edge.Schema = schemaConfig.Posting
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntryWith applies the HasEdge predicate on the "entry" edge with a given conditions (other predicates).
func HasEntryWith(preds ...predicate.Entry) predicate.Posting {
	return predicate.Posting(func(s *sql.Selector) {
		step := newEntryStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Entry
		step.Edge.Schema = schemaConfig.Posting
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.Posting {
	return predicate.Posting(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Account
		step.Edge.Schema = schemaConfig.Posting
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.Posting {
	return predicate.Posting(func(s *sql.Selector) {
		step := newAccountStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Account
		step.Edge.Schema = schemaConfig.Posting
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Posting) predicate.Posting {
	return predicate.Posting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Posting) predicate.Posting {
	return predicate.Posting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Posting) predicate.Posting {
	return predicate.Posting(sql.NotPredicates(p))
}
