name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  auth:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run build
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: apps/auth
          packageManager: bun
          secrets: |
            AUTH_DB_DRIVER
            AUTH_DB_URL
            AUTH_GOOGLE_ID
            AUTH_GOOGLE_SECRET
            AUTH_SECRET
        env:
          AUTH_DB_DRIVER: ${{ secrets.AUTH_DB_DRIVER}}
          AUTH_DB_URL: ${{ secrets.AUTH_DB_URL }}
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
