---
name: "Release"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token}}

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.release_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup workflow variables
        shell: bash
        id: vars
        run: |
          # Retrieve previous release tag
          previous_tag="$(gh release list --limit 1 | awk '{ print $1 }')"
          previous_major="${previous_tag%%\.*}"
          previous_minor="${previous_tag#*.}"
          previous_minor="${previous_minor%.*}"
          previous_patch="${previous_tag##*.}"
          # Determine next release tag
          next_major_minor="$(date +'%Y').$(date +'%-m')"
          if [[ "${previous_major}.${previous_minor}" == "${next_major_minor}" ]]; then
              echo "Month release already exists for year, incrementing patch number by 1"
              next_patch="$((previous_patch + 1))"
          else
              echo "Month release does not exist for year, setting patch number to 0"
              next_patch="0"
          fi

          # Create release
          release_tag="${next_major_minor}.${next_patch}"
          echo "release_tag=${release_tag}" >> $GITHUB_OUTPUT
          echo "previous_tag=${previous_tag}" >> $GITHUB_OUTPUT

      - name: Create Release
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RELEASE_TAG: "${{ steps.vars.outputs.release_tag }}"
        run: |
          gh release create "${RELEASE_TAG}" \
            --repo="${GITHUB_REPOSITORY}" \
            --target=main \
            --title="${RELEASE_TAG}"

      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toTag: ${{ steps.vars.outputs.previous_tag }}
          fromTag: ${{ steps.vars.outputs.release_tag }}

      - name: Update release changelog
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RELEASE_TAG: "${{ steps.vars.outputs.release_tag }}"
        run: |
          gh release edit \
            --repo="${GITHUB_REPOSITORY}" \
            ${RELEASE_TAG} \
            --notes-file CHANGELOG.md

  build:
    name: Build CMS Container
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: |
            maintainer="Anthonius Munthi"
            org.opencontainers.image.author="Anthonius Munthi"
            org.opencontainers.image.version=${{ needs.release.outputs.tag }}
            org.opencontainers.image.description="A demo project on steroids"
          images: |
            ghcr.io/kilip/omed-cms
          tags: |
            ${{ needs.release.outputs.tag }}
            latest

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: "./cms"
          push: true
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
